---
name: auto-test

permissions:
    pull-requests: write
    contents: read

on:
  workflow_dispatch

jobs:

  check_test:
    uses: ./.github/workflows/ansible_linter.yml
    secrets:
      SLACK_TOKEN: ${{secrets.SLACK_API_TOKEN}}
    # with:
    #   branch_name: "devel-miracle"
